### ISSUE TITLE
"filename.sass" is not in the SourceMap.

### ISSUE THREAD

**Issue by Shugar** [brunch/postcss-brunch#10]
Hello! I have a little problem with autoprefixer. 
error: [Error: "app/stylesheets/index.sass" is not in the SourceMap.]

Maybe you can help me? 

```
exports.config =
  files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        'javascripts/vendor.js': /^(?!app)/

    stylesheets:
      joinTo: 'stylesheets/app.css  '

    templates:
      joinTo: 'javascripts/app.js'

  plugins:
    jaded:
      jade:
        pretty: yes

    postcss:
      processors: [
          require('autoprefixer')(['> 1%','last 8 versions'])
      ]
```

```
 "devDependencies": {
    "clean-css-brunch": "~1.7.1",
    "coffee-script-brunch": "~1.8.0",
    "uglify-js-brunch": "~1.7.7",
    "css-brunch": "~1.7.0",
    "javascript-brunch": "~1.7.1",
    "auto-reload-brunch": "~1.7.3",
    "bower": "~1.3.3",
    "jaded-brunch": "~1.7.11",
    "postcss-brunch": "^0.4.x",
    "autoprefixer": "^5.1.0"
  },
  "dependencies": {
    "parse": "^1.5.0",
    "sass-brunch": "^1.8.3"
  }
```
